export interface WalletSeedKol {
  walletAddress: string;
  displayName: string;
  twitterUsername: string;
}

/** Known Solana KOL wallets with nicknames and X handles. */
export const SOLANA_KOL_WALLET_SEED: WalletSeedKol[] = [
  { walletAddress: "8deJ9xeUvXSJwicYptA9mHsU2rN2pDx37KWzkDkEXhU6", displayName: "Cooker", twitterUsername: "CookerFlips" },
  { walletAddress: "8zFZHuSRuDpuAR7J6FzwyF3vKNx4CVW3DFHJerQhc7Zd", displayName: "Pow", twitterUsername: "traderpow" },
  { walletAddress: "7VBTpiiEjkwRbRGHJFUz6o5fWuhPFtAmy8JGhNqwHNnn", displayName: "Brox", twitterUsername: "ohbrox" },
  { walletAddress: "HmBmSYwYEgEZuBUYuDs9xofyqBAkw4ywugB1d7R7sTGh", displayName: "Tobx", twitterUsername: "TobxG" },
  { walletAddress: "mW4PZB45isHmnjGkLpJvjKBzVS5NXzTJ8UDyug4gTsM", displayName: "Dex", twitterUsername: "igndex" },
  { walletAddress: "DNfuF1L62WWyW3pNakVkyGGFzVVhj4Yr52jSmdTyeBHm", displayName: "Gake", twitterUsername: "Ga__ke" },
  { walletAddress: "ATKi3ZvMbo31pbgBgGSGQPDPKEbQ4oGzoDrwG2sms56k", displayName: "Nach", twitterUsername: "NachSOL" },
  { walletAddress: "3kebnKw7cPdSkLRfiMEALyZJGZ4wdiSRvmoN4rD1yPzV", displayName: "Bastille", twitterUsername: "BastilleBtc" },
  { walletAddress: "AVAZvHLR2PcWpDf8BXY4rVxNHYRBytycHkcB5z5QNXYm", displayName: "Ansem", twitterUsername: "blknoiz06" },
  { walletAddress: "215nhcAHjQQGgwpQSJQ7zR26etbjjtVdW74NLzwEgQjP", displayName: "OGAntD", twitterUsername: "0GAntD" },
  { walletAddress: "7i7vHEv87bs135DuoJVKe9c7abentawA5ydfWcWc8iY2", displayName: "ChartFu", twitterUsername: "ChartFuMonkey" },
  { walletAddress: "F5TjPySiUJMdvqMZHnPP85Rc1vErDGV5FR5P2vdVm429", displayName: "Zyaf", twitterUsername: "0xZyaf" },
  { walletAddress: "6m5sW6EAPAHncxnzapi1ZVJNRb9RZHQ3Bj7FD84X9rAF", displayName: "Shocked JS", twitterUsername: "ShockedJS" },
  { walletAddress: "DpNVrtA3ERfKzX4F8Pi2CVykdJJjoNxyY5QgoytAwD26", displayName: "Gorilla Capital", twitterUsername: "gorillacapsol" },
  { walletAddress: "7SDs3PjT2mswKQ7Zo4FTucn9gJdtuW4jaacPA65BseHS", displayName: "Insentos", twitterUsername: "insentos" },
  { walletAddress: "ApRnQN2HkbCn7W2WWiT2FEKvuKJp9LugRyAE1a9Hdz1", displayName: "S", twitterUsername: "runitbackghost" },
  { walletAddress: "9AqzsYXj1M2z8shG6resmM7LNM6GdvsjcjhjRUPc1dNf", displayName: "Cuh", twitterUsername: "quarsays" },
  { walletAddress: "GwoFJFjUTUSWq2EwTz4P2Sznoq9XYLrf8t4q5kbTgZ1R", displayName: "Levis", twitterUsername: "LevisNFT" },
  { walletAddress: "DeVjHYTEZEi7Wvcvfjz8KZMzpuZpijABgutSfXn1BxjX", displayName: "Duke", twitterUsername: "dukezfn" },
  { walletAddress: "41uh7g1DxYaYXdtjBiYCHcgBniV9Wx57b7HU7RXmx1Gg", displayName: "Lowskii", twitterUsername: "Lowskii_gg" },
  { walletAddress: "c3XGUoDSBaJDA8qaJ5pUkCnamMERwZLJBVjxdkNepGo", displayName: "Mog", twitterUsername: "10piecedawg" },
  { walletAddress: "FRbUNvGxYNC1eFngpn7AD3f14aKKTJVC6zSMtvj2dyCS", displayName: "Henn100x", twitterUsername: "henn100x" },
  { walletAddress: "8MaVa9kdt3NW4Q5HyNAm1X5LbR8PQRVDc1W8NMVK88D5", displayName: "Daumen", twitterUsername: "daumeneth" },
  { walletAddress: "m7Kaas3Kd8FHLnCioSjCoSuVDReZ6FDNBVM6HTNYuF7", displayName: "Ferb", twitterUsername: "ferbsol" },
  { walletAddress: "HwRnKq7RPtKHvX9wyHsc1zvfHtGjPQa5tyZtGtbvfXE", displayName: "Jay", twitterUsername: "BitBoyJay" },
  { walletAddress: "FbvUU5qvD9JsU9jp3KDweCpZiVZHLoQBQ1PPCAAbd6FB", displayName: "Profitier", twitterUsername: "profitierr" },
  { walletAddress: "Aen6LKc7sGVPTyjMd5cu9B9XVjL7m9pnvAiP2ZNJC4GZ", displayName: "Aroa", twitterUsername: "AroaOnSol" },
  { walletAddress: "3h65MmPZksoKKyEpEjnWU2Yk2iYT5oZDNitGy5cTaxoE", displayName: "Jidn", twitterUsername: "jidn_w" },
  { walletAddress: "AE3tJDEyUdwBM8ZoUb3iCo563gMbq26JtckfvjcVZbSa", displayName: "Roxo", twitterUsername: "RoxoXBT" },
  { walletAddress: "5AyJw1VNDgTho2chipbVmuGqTuX1fCvVkLneChQkQrw8", displayName: "Bolivian", twitterUsername: "_bolivian" },
  { walletAddress: "Ds8mcuP5r2phg596mLui3ti3PJtVvFRw19Eo9UFdJ5Bc", displayName: "Jazz", twitterUsername: "youngjazzeth" },
  { walletAddress: "2BU3NAzgRA2gg2MpzwwXpA8X4CCRaLgrf6TY1FKfJPX2", displayName: "Issa", twitterUsername: "issathecooker" },
  { walletAddress: "9vWutdTBs66hWkeCmxaLFpkKy4q5RSe8DsFjfdxj5yFA", displayName: "Dutch", twitterUsername: "0xDutch_" },
  { walletAddress: "5wcc13mXoyqe6qh2iHH5GFknojoJ7y13ZPx9K4NXTuo3", displayName: "Dolo", twitterUsername: "doloxbt" },
  { walletAddress: "GM7Hrz2bDq33ezMtL6KGidSWZXMWgZ6qBuugkb5H8NvN", displayName: "Beaver", twitterUsername: "beaverd" },
  { walletAddress: "6S8GezkxYUfZy9JPtYnanbcZTMB87Wjt1qx3c6ELajKC", displayName: "Nyhrox", twitterUsername: "nyhrox" },
  { walletAddress: "4EsY8HQB4Ak65diFrSHjwWhKSGC8sKmnzyusM993gk2w", displayName: "Prosciutto", twitterUsername: "prosciuttosol" },
  { walletAddress: "B7FDzJnb7DLYH1A37tKEFss1RRSz5C7MYgTRRMaWzBqa", displayName: "Lucas", twitterUsername: "LockedInLucas" },
  { walletAddress: "9K18MstUaXmSFSBoa9qDTqWTnYhTZqdgEhuKRTVRgh6g", displayName: "Sabby", twitterUsername: "sabby_eth" },
  { walletAddress: "4AHgEkTsGqY77qtde4UJn9yZCrbGcM7UM3vjT3qM4G5H", displayName: "BagCalls", twitterUsername: "BagCalls" },
  { walletAddress: "D2wBctC1K2mEtA17i8ZfdEubkiksiAH2j8F7ri3ec71V", displayName: "Dior", twitterUsername: "Dior100x" },
  { walletAddress: "42nsEk51owYM3uciuRvFerqK77yhXZyjBLRgkDzJPV2g", displayName: "Izzy", twitterUsername: "degenIzzy" },
  { walletAddress: "6Qs6joB349h7zu1z9xRgPgMSmpBYLDQb2wtAecY4LysH", displayName: "Chefin", twitterUsername: "Chefin100x" },
  { walletAddress: "HCQb4Qrtk4qCfChDH8XvM5onymmCSmRj9bddV6QCPdRe", displayName: "Rektober", twitterUsername: "rektober" },
  { walletAddress: "iWinRYGEWcaFFqWfgjh28jnqWL72XUMmUfhADpTQaRL", displayName: "Imperator", twitterUsername: "imperooterxbt" },
  { walletAddress: "HUS9ErdrDqpqQePbmfgJUTnDTE6eZ8ES62a25RihSK9U", displayName: "Hustler", twitterUsername: "JoeVargas" },
  { walletAddress: "525LueqAyZJueCoiisfWy6nyh4MTvmF4X9jSqi6efXJT", displayName: "Joji", twitterUsername: "metaversejoji" },
  { walletAddress: "7SvvTJSwcpNQCDGEt14zuoPFoSsaveGd7UWgiJGQLAHN", displayName: "Mero", twitterUsername: "MeroFN" },
  { walletAddress: "3FDci33mzMKNdNxzSS9D13XyNZQAdfmpvtDZLWPbZiAU", displayName: "Sachs", twitterUsername: "gudmansachs" },
  { walletAddress: "9Vk7pkBZ9KFJmzaPzNYjGedyz8qoKMQtnYyYi2AehNMT", displayName: "Xelf", twitterUsername: "xelf_sol" },
  { walletAddress: "8YYDiCbPd4nM8TxrQEVdPA4aG8jys8R7Z1kKsgPL4pwh", displayName: "Michi", twitterUsername: "michigems" },
  { walletAddress: "4vw54BmAogeRV3vPKWyFet5yf8DTLcREzdSzx4rw9Ud9", displayName: "Decu", twitterUsername: "Decu0x" },
  { walletAddress: "4jFPYSoUTRaFbFDJp9QpA1J5xJmMJYoWhiFTpoLPq6X", displayName: "Merk", twitterUsername: "MerkTrading" },
  { walletAddress: "9yGxZ43ngT7LvwquVdUAYPvJzVyY65cS6mQvuJXjTEUc", displayName: "Xet", twitterUsername: "xet" },
  { walletAddress: "4F2AHuw55m9ojKpFfsofmhAwB979ECVRFVurEam4phqU", displayName: "Lunix", twitterUsername: "SolLunix" },
  { walletAddress: "D6JrzpAKtLT4XQmgVKxdKZwFxJ4HmZWVKmMfKEK4av6d", displayName: "Solana Plays", twitterUsername: "SolanaPlays" },
  { walletAddress: "DBmRHNbSsVX8F6NyVaaaiuGdwo1aYGawiy3jfNcvXYSC", displayName: "Bobby", twitterUsername: "retardmode" },
  { walletAddress: "3mPypxb7ViYEdLv4siFmESvY5w5ZKknwgmB4TPcZ77qe", displayName: "Carti The Menace", twitterUsername: "CartiTheMenace" },
  { walletAddress: "J2B5fnm2DAAUAGa4EaegwQFoYaN6B5FerGA5sjtQoaGM", displayName: "Dan176", twitterUsername: "176Dan" },
  { walletAddress: "B3beyovNKBo4wF1uFrfGfpVeyEHjFyJPmEBciz7kpnoS", displayName: "CC2", twitterUsername: "CC2Ventures" },
  { walletAddress: "EAnB5151L8ejp3SM6haLgyv3snk6oqc8acKgWEg9T5J", displayName: "Frosty", twitterUsername: "ohFrostyyy" },
  { walletAddress: "ExKCuoAzJCgCVjU3CvNoL8vVrdESTWkx3ubj6rQXwQM4", displayName: "TheDefiApe", twitterUsername: "TheDefiApe" },
  { walletAddress: "C4BWYccLsbeHgZzVupFZJGvJK2nQpn8em9WtzURH4gZW", displayName: "Obijai", twitterUsername: "Obijai" },
  { walletAddress: "FEYmfSL4B3Hhk5BzyEJNpHRiwAoMvzdNe2oa1UTKmbYT", displayName: "Idontpaytaxes", twitterUsername: "untaxxable" },
  { walletAddress: "HrCPnDvDgbpbFxKxer6Pw3qEcfAQQNNjb6aJNFWgTEng", displayName: "0xWinged", twitterUsername: "0xExorcized" },
  { walletAddress: "Ebk5ATdfrCuKi27dHZaw5YYsfREEzvvU8xeBhMxQoex6", displayName: "Sully", twitterUsername: "sullyfromDeets" },
  { walletAddress: "AGnd5WTHMUbyK3kjjQPdQFM3TbWcuPTtkwBFWVUwiCLu", displayName: "Angi", twitterUsername: "angitradez" },
  { walletAddress: "CSHktdVEmJybwNR9ft3sDfSc2UKgTPZZ8km26XfHYZDt", displayName: "Lynk", twitterUsername: "lynk0x" },
  { walletAddress: "86AEJExyjeNNgcp7GrAvCXTDicf5aGWgoERbXFiG1EdD", displayName: "Publix", twitterUsername: "publixplays" },
  { walletAddress: "3nvC8cSrEBqFEXZjUpKfwZMPk7xYdqcnoxmFBjXiizVX", displayName: "Value & Time", twitterUsername: "valueandtime" },
  { walletAddress: "H9h6UV9cwWWogcTZ5gbzQ6Z3dYDNaiJ3mUWw3aGnE3Mc", displayName: "Monarky", twitterUsername: "MonarkyMemes" },
  { walletAddress: "HLv6yCEpgjQV9PcKsvJpem8ESyULTyh9HjHn9CtqSek1", displayName: "Lyxe", twitterUsername: "cryptolyxe" },
  { walletAddress: "CqQKv6XdrMWrz3YuSwqTTcVoQK5eu4zNo3hps3M1Q3yo", displayName: "Jaden", twitterUsername: "JadenOnChain" },
  { walletAddress: "DsqRyTUh1R37asYcVf1KdX4CNnz5DKEFmnXvgT4NfTPE", displayName: "Classic", twitterUsername: "mrclassic33" },
  { walletAddress: "Gv7CnRo2L2SJ583XEfoKHKbmWK3wNoBDxVoJqMKJR4Nu", displayName: "Robo", twitterUsername: "roboPBOC" },
  { walletAddress: "7ABz8qEFZTHPkovMDsmQkm64DZWN5wRtU7LEtD2ShkQ6", displayName: "Red", twitterUsername: "redwithbag" },
  { walletAddress: "4Be9CvxqHW6BYiRAxW9Q3xu1ycTMWaL5z8NX4HR3ha7t", displayName: "Mitch", twitterUsername: "1solinfeb" },
  { walletAddress: "EdDCRfDDeiiDXdntrP59abH4DXHFNU48zpMPYisDMjA7", displayName: "Mezoteric", twitterUsername: "mezoteric" },
  { walletAddress: "DYAn4XpAkN5mhiXkRB7dGq4Jadnx6XYgu8L5b3WGhbrt", displayName: "The Doc", twitterUsername: "KayTheDoc" },
  { walletAddress: "F2SuErm4MviWJ2HzKXk2nuzBC6xe883CFWUDCPz6cyWm", displayName: "Earl", twitterUsername: "earlTrades" },
  { walletAddress: "2kv8X2a9bxnBM8NKLc6BBTX2z13GFNRL4oRotMUJRva9", displayName: "Gh0stee", twitterUsername: "4GH0STEE" },
  { walletAddress: "5B52w1ZW9tuwUduueP5J7HXz5AcGfruGoX6YoAudvyxG", displayName: "Yenni", twitterUsername: "Yennii56" },
  { walletAddress: "831yhv67QpKqLBJjbmw2xoDUeeFHGUx8RnuRj9imeoEs", displayName: "Trey", twitterUsername: "treysocial" },
  { walletAddress: "4DdrfiDHpmx55i4SPssxVzS9ZaKLb8qr45NKY9Er9nNh", displayName: "Mr. Frog", twitterUsername: "TheMisterFrog" },
  { walletAddress: "AbcX4XBm7DJ3i9p29i6sU8WLmiW4FWY5tiwB9D6UBbcE", displayName: "404Flipped", twitterUsername: "404flipped" },
  { walletAddress: "34ZEH778zL8ctkLwxxERLX5ZnUu6MuFyX9CWrs8kucMw", displayName: "Groovy", twitterUsername: "0xGroovy" },
  { walletAddress: "5x8tfrJSn4Pt5gjQEMWDnoLvAzZ8rgJVTXiTpcwhbxmN", displayName: "Tahi", twitterUsername: "Tahifn" },
  { walletAddress: "7tiRXPM4wwBMRMYzmywRAE6jveS3gDbNyxgRrEoU6RLA", displayName: "Qtdegen", twitterUsername: "qtdegen" },
  { walletAddress: "2CXbN6nuTTb4vCrtYM89SfQHMMKGPAW4mvFe6Ht4Yo6z", displayName: "MoneyMaykah", twitterUsername: "moneymaykah_" },
  { walletAddress: "7N4bAyZX6z39RozQh7GC8VQmgjvjkkWmSyAt1wdMjEmq", displayName: "Zinc", twitterUsername: "Zinc_ETH" },
  { walletAddress: "E33jP6RWVpGkv3fDVbuR5Ee6ak42tTKW9yYszqERtobs", displayName: "Jerry", twitterUsername: "chefjerrry" },
  { walletAddress: "9yYya3F5EJoLnBNKW6z4bZvyQytMXzDcpU5D6yYr4jqL", displayName: "Loopierr", twitterUsername: "Loopierr" },
  { walletAddress: "9FNz4MjPUmnJqTf6yEDbL1D4SsHVh7uA8zRHhR5K138r", displayName: "Danny", twitterUsername: "0xSevere" },
  { walletAddress: "2YJbcB9G8wePrpVBcT31o8JEed6L3abgyCjt5qkJMymV", displayName: "Al4n", twitterUsername: "Al4neu" },
  { walletAddress: "831qmkeGhfL8YpcXuhrug6nHj1YdK3aXMDQUCo85Auh1", displayName: "Meechie", twitterUsername: "973Meech" },
  { walletAddress: "6LChaYRYtEYjLEHhzo4HdEmgNwu2aia8CM8VhR9wn6n7", displayName: "Assasin.eth", twitterUsername: "assasin_eth" },
  { walletAddress: "8rvAsDKeAcEjEkiZMug9k8v1y8mW6gQQiMobd89Uy7qR", displayName: "Casino", twitterUsername: "casino616" },
  { walletAddress: "GJA1HEbxGnqBhBifH9uQauzXSB53to5rhDrzmKxhSU65", displayName: "Latuche", twitterUsername: "Latuche95" },
  { walletAddress: "BXNiM7pqt9Ld3b2Hc8iT3mA5bSwoe9CRrtkSUs15SLWN", displayName: "Absol", twitterUsername: "absolquant" },
  { walletAddress: "4WPTQA7BB4iRdrPhgNpJihGcxKh8T43gLjMn5PbEVfQw", displayName: "Oura", twitterUsername: "Oura456" },
  { walletAddress: "7iabBMwmSvS4CFPcjW2XYZY53bUCHzXjCFEFhxeYP4CY", displayName: "Leens", twitterUsername: "leensx100" },
  { walletAddress: "5TuiERc4X7EgZTxNmj8PHgzUAfNHZRLYHKp4DuiWevXv", displayName: "Rev", twitterUsername: "solrevv" },
  { walletAddress: "BCagckXeMChUKrHEd6fKFA1uiWDtcmCXMsqaheLiUPJd", displayName: "dv", twitterUsername: "vibed333" },
  { walletAddress: "BTf4A2exGK9BCVDNzy65b9dUzXgMqB4weVkvTMFQsadd", displayName: "Kev", twitterUsername: "Kevsznx" },
  { walletAddress: "96sErVjEN7LNJ6Uvj63bdRWZxNuBngj56fnT9biHLKBf", displayName: "Orange", twitterUsername: "OrangeSBS" },
  { walletAddress: "4S9U8HckRngscHWrW418cG6Suw62dhEZzmyrT2hxSye5", displayName: "Polar", twitterUsername: "polarsterrr" },
  { walletAddress: "EHg5YkU2SZBTvuT87rUsvxArGp3HLeye1fXaSDfuMyaf", displayName: "TIL", twitterUsername: "tilcrypto" },
  { walletAddress: "EaVboaPxFCYanjoNWdkxTbPvt57nhXGu5i6m9m6ZS2kK", displayName: "Danny", twitterUsername: "cladzsol" },
  { walletAddress: "F72vY99ihQsYwqEDCfz7igKXA5me6vN2zqVsVUTpw6qL", displayName: "Jalen", twitterUsername: "RipJalens" },
  { walletAddress: "4BdKaxN8G6ka4GYtQQWk4G4dZRUTX2vQH9GcXdBREFUk", displayName: "Jijo", twitterUsername: "jijo_exe" },
  { walletAddress: "5rkPDK4JnVAumgzeV2Zu8vjggMTtHdDtrsd5o9dhGZHD", displayName: "Dave Portnoy", twitterUsername: "stoolpresidente" },
  { walletAddress: "BCnqsPEtA1TkgednYEebRpkmwFRJDCjMQcKZMMtEdArc", displayName: "Kreo", twitterUsername: "kreo444" },
  { walletAddress: "DfMxre4cKmvogbLrPigxmibVTTQDuzjdXojWzjCXXhzj", displayName: "Euris", twitterUsername: "Euris_JT" },
  { walletAddress: "CyaE1VxvBrahnPWkqm5VsdCvyS2QmNht2UFrKJHga54o", displayName: "Cented", twitterUsername: "Cented7" },
  { walletAddress: "CRVidEDtEUTYZisCxBZkpELzhQc9eauMLR3FWg74tReL", displayName: "Frank", twitterUsername: "frankdegods" },
  { walletAddress: "AJ6MGExeK7FXmeKkKPmALjcdXVStXYokYNv9uVfDRtvo", displayName: "Tim", twitterUsername: "timmpix1" },
  { walletAddress: "73LnJ7G9ffBDjEBGgJDdgvLUhD5APLonKrNiHsKDCw5B", displayName: "Waddles", twitterUsername: "waddles_eth" },
  { walletAddress: "JDd3hy3gQn2V982mi1zqhNqUw1GfV2UL6g76STojCJPN", displayName: "West", twitterUsername: "ratwizardx" },
  { walletAddress: "3LYtEmYerFPeXgu1c9Y4553oMk2qVdcxiwWzDjzMkwPx", displayName: "awkchan45", twitterUsername: "awkchan45" },
  { walletAddress: "AeLaMjzxErZt4drbWVWvcxpVyo8p94xu5vrg41eZPFe3", displayName: "s1mple_s1mple", twitterUsername: "s1mple_s1mple" },
  { walletAddress: "UxuuMeyX2pZPHmGZ2w3Q8MysvExCAquMtvEfqp2etvm", displayName: "pandoraflips", twitterUsername: "pandoraflips" },
  { walletAddress: "FAicXNV5FVqtfbpn4Zccs71XcfGeyxBSGbqLDyDJZjke", displayName: "radiance", twitterUsername: "radiancebrr" },
];
